pipelines:
    branches:
      master:
        - step:
           script:
             - git remote add sync git@github.com:Citeck/ecos-notifications-lib.git
             - git checkout master
             - git pull
             - git push sync master
